spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  mail:
    host: ""
  flyway:
    locations: classpath:/db/migration/h2
  jpa:
    hibernate:
      ddl-auto: none

cicoffee:
  auth:
    jwt:
      signing-key: ""
