spring:
  jpa.properties.hibernate.jdbc.time_zone: UTC
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration


cicoffee:
  mail:
    from: info@pausa-cafe.ga
  auth:
    jwt:
      expires-in: 3600
      refresh-token-expires-in: 182
